import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopthree">DesktopThree</Link>
        </li>
        <li>
          <Link to="/productdetailspageproductdescription">
            ProductDetailsPageProductdescription
          </Link>
        </li>
        <li>
          <Link to="/loginflowmobile">LoginFlowMobile</Link>
        </li>
        <li>
          <Link to="/loginflowotp">LoginFlowOTP</Link>
        </li>
        <li>
          <Link to="/cartpage">CartPage</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
